
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Rui
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crud_PC_Escritorio = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_host = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_mascaraRed = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_ram = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_storage = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_tipoStorage = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tarjeta = new javax.swing.JList<>();
        bt_agregarEscritorio = new javax.swing.JButton();
        crud_PC_Laptop = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_hostLaptop = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_ipLaptop = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_mascaraLaptop = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_defPantalla = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_RGB = new javax.swing.JList<>();
        bt_agregarLaptop = new javax.swing.JButton();
        crud_main = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        bt_crear = new javax.swing.JButton();
        bt_listar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        crud_choose = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        bt_PC_Escritorio = new javax.swing.JButton();
        bt_PC_Laptop = new javax.swing.JButton();
        crud_lista = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea_lista = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        bt_salirlLista = new javax.swing.JButton();
        crud_eliminar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cb_listaEliminar = new javax.swing.JComboBox<>();
        bt_Eliminar = new javax.swing.JButton();
        bt_salirEliminar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        bt_ingresar = new javax.swing.JButton();
        bt_crudPC = new javax.swing.JButton();

        crud_PC_Escritorio.setPreferredSize(new java.awt.Dimension(415, 330));
        crud_PC_Escritorio.setResizable(false);
        crud_PC_Escritorio.setSize(new java.awt.Dimension(415, 330));

        jPanel7.setMaximumSize(new java.awt.Dimension(415, 330));
        jPanel7.setMinimumSize(new java.awt.Dimension(415, 330));
        jPanel7.setPreferredSize(new java.awt.Dimension(415, 330));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Agregar PC de Escritorio");
        jLabel3.setToolTipText("");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 210, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Host:");
        jLabel1.setToolTipText("");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 16));

        tf_host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hostActionPerformed(evt);
            }
        });
        jPanel7.add(tf_host, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("IP:");
        jLabel4.setToolTipText("");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 30, 20));
        jPanel7.add(tf_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mascara de Red:");
        jLabel5.setToolTipText("");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 20));
        jPanel7.add(tf_mascaraRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 260, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Capacidad de RAM:");
        jLabel10.setToolTipText("");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));
        jPanel7.add(tf_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Capacidad de Almacenamiento:");
        jLabel11.setToolTipText("");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, 20));
        jPanel7.add(tf_storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 100, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tipo de Almacenamiento:");
        jLabel12.setToolTipText("");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 20));
        jPanel7.add(tf_tipoStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("¿Tiene tarjeta gráfica?");
        jLabel13.setToolTipText("");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, -1));

        lista_tarjeta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Si", "No" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista_tarjeta);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 60, 50));

        bt_agregarEscritorio.setText("Agregar");
        bt_agregarEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarEscritorioActionPerformed(evt);
            }
        });
        jPanel7.add(bt_agregarEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        javax.swing.GroupLayout crud_PC_EscritorioLayout = new javax.swing.GroupLayout(crud_PC_Escritorio.getContentPane());
        crud_PC_Escritorio.getContentPane().setLayout(crud_PC_EscritorioLayout);
        crud_PC_EscritorioLayout.setHorizontalGroup(
            crud_PC_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crud_PC_EscritorioLayout.setVerticalGroup(
            crud_PC_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        crud_PC_Laptop.setPreferredSize(new java.awt.Dimension(415, 330));
        crud_PC_Laptop.setResizable(false);
        crud_PC_Laptop.setSize(new java.awt.Dimension(415, 330));

        jPanel8.setMaximumSize(new java.awt.Dimension(415, 330));
        jPanel8.setMinimumSize(new java.awt.Dimension(415, 330));
        jPanel8.setPreferredSize(new java.awt.Dimension(415, 330));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Agregar Laptop");
        jLabel6.setToolTipText("");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 210, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Host:");
        jLabel7.setToolTipText("");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));
        jPanel8.add(tf_hostLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 320, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("IP:");
        jLabel8.setToolTipText("");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, 20));
        jPanel8.add(tf_ipLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 340, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mascara de Red:");
        jLabel9.setToolTipText("");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        tf_mascaraLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mascaraLaptopActionPerformed(evt);
            }
        });
        jPanel8.add(tf_mascaraLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 260, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Marca:");
        jLabel14.setToolTipText("");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 20));
        jPanel8.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 300, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Definición de Pantalla:");
        jLabel15.setToolTipText("");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 20));

        tf_defPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_defPantallaActionPerformed(evt);
            }
        });
        jPanel8.add(tf_defPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("¿Es de teclado RGB? ");
        jLabel16.setToolTipText("");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 30));

        lista_RGB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Si", "No" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lista_RGB);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 60, 50));

        bt_agregarLaptop.setText("Agregar");
        bt_agregarLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarLaptopActionPerformed(evt);
            }
        });
        jPanel8.add(bt_agregarLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        javax.swing.GroupLayout crud_PC_LaptopLayout = new javax.swing.GroupLayout(crud_PC_Laptop.getContentPane());
        crud_PC_Laptop.getContentPane().setLayout(crud_PC_LaptopLayout);
        crud_PC_LaptopLayout.setHorizontalGroup(
            crud_PC_LaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crud_PC_LaptopLayout.setVerticalGroup(
            crud_PC_LaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        crud_main.setMinimumSize(new java.awt.Dimension(400, 300));
        crud_main.setPreferredSize(new java.awt.Dimension(700, 500));
        crud_main.setResizable(false);
        crud_main.setSize(new java.awt.Dimension(700, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setText("< C R U D >");
        jLabel18.setToolTipText("");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        bt_crear.setText("CREAR");
        bt_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearActionPerformed(evt);
            }
        });
        jPanel1.add(bt_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 220, 50));

        bt_listar.setText("LISTAR");
        bt_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 220, 50));

        bt_eliminar.setText("ELIMINAR");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 220, 50));

        bt_salir.setText("SALIR");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        jPanel1.add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 220, 50));

        javax.swing.GroupLayout crud_mainLayout = new javax.swing.GroupLayout(crud_main.getContentPane());
        crud_main.getContentPane().setLayout(crud_mainLayout);
        crud_mainLayout.setHorizontalGroup(
            crud_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crud_mainLayout.setVerticalGroup(
            crud_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        crud_choose.setPreferredSize(new java.awt.Dimension(700, 500));
        crud_choose.setResizable(false);
        crud_choose.setSize(new java.awt.Dimension(700, 500));

        jPanel5.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel5.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel5.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("< C R U D >");
        jLabel19.setToolTipText("");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 6, -1, -1));

        bt_PC_Escritorio.setText("PC de Escritorio");
        bt_PC_Escritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PC_EscritorioActionPerformed(evt);
            }
        });
        jPanel5.add(bt_PC_Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, 38));

        bt_PC_Laptop.setText("Laptop");
        bt_PC_Laptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_PC_LaptopMouseClicked(evt);
            }
        });
        bt_PC_Laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PC_LaptopActionPerformed(evt);
            }
        });
        jPanel5.add(bt_PC_Laptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 38));

        javax.swing.GroupLayout crud_chooseLayout = new javax.swing.GroupLayout(crud_choose.getContentPane());
        crud_choose.getContentPane().setLayout(crud_chooseLayout);
        crud_chooseLayout.setHorizontalGroup(
            crud_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        crud_chooseLayout.setVerticalGroup(
            crud_chooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        crud_lista.setMaximumSize(new java.awt.Dimension(415, 330));
        crud_lista.setMinimumSize(new java.awt.Dimension(415, 330));
        crud_lista.setPreferredSize(new java.awt.Dimension(415, 330));
        crud_lista.setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(415, 330));
        jPanel2.setMinimumSize(new java.awt.Dimension(415, 330));
        jPanel2.setPreferredSize(new java.awt.Dimension(415, 330));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea_lista.setColumns(20);
        txtArea_lista.setRows(5);
        jScrollPane3.setViewportView(txtArea_lista);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("< L I S T A D O >");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        bt_salirlLista.setText("SALIR");
        bt_salirlLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_salirlListaMouseClicked(evt);
            }
        });
        bt_salirlLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirlListaActionPerformed(evt);
            }
        });
        jPanel2.add(bt_salirlLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 230, 38));

        javax.swing.GroupLayout crud_listaLayout = new javax.swing.GroupLayout(crud_lista.getContentPane());
        crud_lista.getContentPane().setLayout(crud_listaLayout);
        crud_listaLayout.setHorizontalGroup(
            crud_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        crud_listaLayout.setVerticalGroup(
            crud_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        crud_eliminar.setMaximumSize(new java.awt.Dimension(700, 500));
        crud_eliminar.setMinimumSize(new java.awt.Dimension(700, 500));
        crud_eliminar.setPreferredSize(new java.awt.Dimension(700, 500));
        crud_eliminar.setResizable(false);

        jPanel3.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setText("< E L I M I N A R >");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        cb_listaEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cb_listaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 330, 50));

        bt_Eliminar.setText("ELIMINAR");
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(bt_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 150, 50));

        bt_salirEliminar.setText("SALIR");
        bt_salirEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(bt_salirEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, 50));

        javax.swing.GroupLayout crud_eliminarLayout = new javax.swing.GroupLayout(crud_eliminar.getContentPane());
        crud_eliminar.getContentPane().setLayout(crud_eliminarLayout);
        crud_eliminarLayout.setHorizontalGroup(
            crud_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        crud_eliminarLayout.setVerticalGroup(
            crud_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 250));
        setMinimumSize(new java.awt.Dimension(500, 250));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 250));

        jPanel6.setMaximumSize(new java.awt.Dimension(500, 250));
        jPanel6.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 250));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("< B I E N V E N I D O >");
        jLabel20.setToolTipText("");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        bt_ingresar.setText("INGRESAR A PC");
        bt_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingresarActionPerformed(evt);
            }
        });
        jPanel6.add(bt_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 220, 70));

        bt_crudPC.setText("CRUD PC");
        bt_crudPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crudPCMouseClicked(evt);
            }
        });
        bt_crudPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crudPCActionPerformed(evt);
            }
        });
        jPanel6.add(bt_crudPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_PC_EscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PC_EscritorioActionPerformed
        // TODO add your handling code here:
        crud_PC_Escritorio.setVisible(true);
        crud_choose.setVisible(false);
    }//GEN-LAST:event_bt_PC_EscritorioActionPerformed

    private void bt_PC_LaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_PC_LaptopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_PC_LaptopMouseClicked

    private void bt_PC_LaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PC_LaptopActionPerformed
        // TODO add your handling code here:
        crud_PC_Laptop.setVisible(true);
        crud_choose.setVisible(false);
    }//GEN-LAST:event_bt_PC_LaptopActionPerformed

    private void bt_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        boolean check = true;
        do {
            Scanner consola = new Scanner(System.in);
            System.out.print("Ingrese una dirección IP: ");
            String ip = consola.next();
            int numLista = 0;
            for (PC pc : listPC) {
                if (ip.equals(pc.getIp())) {
                } else {
                    check = false;
                    numLista++;
                }
            }
            if (check == true) {
                String opcion = "";
                do {
                    System.out.print(listPC.get(numLista).getHostName() + "#");
                    opcion = consola.next();
                    switch (opcion) {
                        case "ping_":
                            break;
                        case "show":
                            break;
                        case "exit":
                            check = false;
                            break;
                    }
                } while (opcion != "exit");
            }
        } while (check == true);
        this.setVisible(true);
    }//GEN-LAST:event_bt_ingresarActionPerformed

    private void bt_crudPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crudPCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crudPCMouseClicked

    private void bt_crudPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crudPCActionPerformed
        // TODO add your handling code here:{
        crud_main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_crudPCActionPerformed

    private void tf_defPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_defPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_defPantallaActionPerformed

    private void bt_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearActionPerformed
        // TODO add your handling code here:
        crud_choose.setVisible(true);
        crud_main.setVisible(false);
    }//GEN-LAST:event_bt_crearActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        crud_main.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_agregarEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarEscritorioActionPerformed
        // TODO add your handling code here:
        boolean tarjetaGrafica = false;
        String tarjeta = lista_tarjeta.getSelectedValue();
        if (tarjeta.equals("Si")) {
            tarjetaGrafica = true;
        }
        boolean sameIP = false;
        for (PC pc : listPC) {
            if (pc.getIp().equals(tf_ip.getText())) {
                sameIP = true;
            }
        }
        String mascaraTK[] = tf_mascaraLaptop.getText().split(".");
        if (sameIP == false && (mascaraTK[0].equals("255") && mascaraTK[1].equals("255") && mascaraTK[2].equals("255")
                && (mascaraTK[3].equals("192") || mascaraTK[3].equals("224") || mascaraTK[3].equals("240") || mascaraTK[3].equals("248") || mascaraTK[3].equals("252")
                || mascaraTK[3].equals("254") || mascaraTK[3].equals("255")))) {
            int ram = Integer.parseInt(tf_ram.getText());
            int storage = Integer.parseInt(tf_storage.getText());
            PC_Escritorio pc = new PC_Escritorio(ram, storage, tf_tipoStorage.getText(), tarjetaGrafica, tf_ip.getText(), tf_mascaraRed.getText(), tf_host.getText());
            listPC.add(pc);
            crud_PC_Escritorio.setVisible(false);
            crud_main.setVisible(true);
        } else {
            tf_host.setText("");
            tf_ip.setText("");
            tf_mascaraRed.setText("");
            tf_ram.setText("");
            tf_storage.setText("");
            tf_tipoStorage.setText("");
        }
    }//GEN-LAST:event_bt_agregarEscritorioActionPerformed

    private void bt_agregarLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarLaptopActionPerformed
        // TODO add your handling code here:
        boolean rgb = false;
        String tarjeta = lista_tarjeta.getSelectedValue();
        if (tarjeta.equals("Si")) {
            rgb = true;
        }
        boolean sameIP = false;
        for (PC pc : listPC) {
            if (pc.getIp().equals(tf_ipLaptop.getText())) {
                sameIP = true;
            }
        }
        String mascaraTK[] = tf_mascaraLaptop.getText().split(".");
        if (sameIP == false && (mascaraTK[0].equals("255") && mascaraTK[1].equals("255") && mascaraTK[2].equals("255")
                && (mascaraTK[3].equals("192") || mascaraTK[3].equals("224") || mascaraTK[3].equals("240") || mascaraTK[3].equals("248") || mascaraTK[3].equals("252")
                || mascaraTK[3].equals("254") || mascaraTK[3].equals("255")))) {
            Laptop laptop = new Laptop(tf_marca.getText(), tf_defPantalla.getText(), rgb, tf_ipLaptop.getText(), tf_mascaraLaptop.getText(), tf_hostLaptop.getText());
            listPC.add(laptop);
            crud_PC_Laptop.setVisible(false);
            crud_main.setVisible(true);
        } else {
            tf_hostLaptop.setText("");
            tf_ipLaptop.setText("");
            tf_mascaraLaptop.setText("");
            tf_marca.setText("");
            tf_defPantalla.setText("");

        }

    }//GEN-LAST:event_bt_agregarLaptopActionPerformed

    private void tf_hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hostActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_hostActionPerformed

    private void tf_mascaraLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mascaraLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mascaraLaptopActionPerformed

    private void bt_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarActionPerformed
        // TODO add your handling code here:
        crud_lista.setVisible(true);
        crud_main.setVisible(false);
        txtArea_lista.setText(listPC.toString());
    }//GEN-LAST:event_bt_listarActionPerformed

    private void bt_salirlListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirlListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_salirlListaActionPerformed

    private void bt_salirlListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salirlListaMouseClicked
        // TODO add your handling code here:
        crud_lista.setVisible(false);
        crud_main.setVisible(true);
    }//GEN-LAST:event_bt_salirlListaMouseClicked

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = new DefaultListModel<String>();
        model.addAll(listPC);
        cb_listaEliminar.setModel((ComboBoxModel<String>) model);
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        // TODO add your handling code here:
        for (PC pc : listPC) {
            if (cb_listaEliminar.getSelectedItem().equals(pc)) {
                listPC.remove(pc);
            }
        }
    }//GEN-LAST:event_bt_EliminarActionPerformed

    private void bt_salirEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirEliminarActionPerformed
        // TODO add your handling code here:
        crud_eliminar.setVisible(false);
        crud_main.setVisible(true);
    }//GEN-LAST:event_bt_salirEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JButton bt_PC_Escritorio;
    private javax.swing.JButton bt_PC_Laptop;
    private javax.swing.JButton bt_agregarEscritorio;
    private javax.swing.JButton bt_agregarLaptop;
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_crudPC;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JButton bt_salirEliminar;
    private javax.swing.JButton bt_salirlLista;
    private javax.swing.JComboBox<String> cb_listaEliminar;
    private javax.swing.JFrame crud_PC_Escritorio;
    private javax.swing.JFrame crud_PC_Laptop;
    private javax.swing.JFrame crud_choose;
    private javax.swing.JFrame crud_eliminar;
    private javax.swing.JFrame crud_lista;
    private javax.swing.JFrame crud_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista_RGB;
    private javax.swing.JList<String> lista_tarjeta;
    private javax.swing.JTextField tf_defPantalla;
    private javax.swing.JTextField tf_host;
    private javax.swing.JTextField tf_hostLaptop;
    private javax.swing.JTextField tf_ip;
    private javax.swing.JTextField tf_ipLaptop;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_mascaraLaptop;
    private javax.swing.JTextField tf_mascaraRed;
    private javax.swing.JTextField tf_ram;
    private javax.swing.JTextField tf_storage;
    private javax.swing.JTextField tf_tipoStorage;
    private javax.swing.JTextArea txtArea_lista;
    // End of variables declaration//GEN-END:variables
    ArrayList<PC> listPC = new ArrayList();
}
